@echo off
REM program_lpc4330.bat - Program LPC4330 via OpenOCD/JTAG (Windows)
REM Drop-in script for programming the drone firmware

echo ==========================================
echo  Drone Firmware - Programming Script
echo ==========================================
echo.

REM Check for firmware file
if not exist "build_lpc4330\drone_firmware.hex" (
    if not exist "build_lpc4330\drone_firmware.elf" (
        echo ERROR: No firmware file found!
        echo Please build the firmware first:
        echo   build_lpc4330.bat
        pause
        exit /b 1
    )
)

REM Check for OpenOCD
where openocd >nul 2>&1
if errorlevel 1 (
    echo WARNING: OpenOCD not found!
    echo.
    echo Alternative programming methods:
    echo   1. Use firmware_uploader.py GUI
    echo   2. Use LPCScrypt (NXP's tool)
    echo   3. Use Flash Magic
    echo   4. Use DFU mode if bootloader present
    echo.
    echo To install OpenOCD:
    echo   - Download from: https://openocd.org/
    echo   - Or use: winget install openocd
    echo.
    set /p choice="Continue with GUI uploader? (y/n): "
    if /i "%choice%"=="y" (
        python firmware_uploader.py
        exit /b 0
    ) else (
        exit /b 1
    )
)

echo OpenOCD found:
openocd --version 2>&1 | findstr "Open On-Chip Debugger"
echo.

REM Check for OpenOCD configuration
if not exist "openocd_lpc4330.cfg" (
    echo Creating OpenOCD configuration file...
    
    echo # OpenOCD configuration for LPC4330> openocd_lpc4330.cfg
    echo # Auto-generated by program_lpc4330.bat>> openocd_lpc4330.cfg
    echo.>> openocd_lpc4330.cfg
    echo source [find interface/stlink.cfg]>> openocd_lpc4330.cfg
    echo source [find target/lpc4350.cfg]>> openocd_lpc4330.cfg
    echo.>> openocd_lpc4330.cfg
    echo adapter speed 4000>> openocd_lpc4330.cfg
    echo.>> openocd_lpc4330.cfg
    echo init>> openocd_lpc4330.cfg
    echo reset halt>> openocd_lpc4330.cfg
    echo.>> openocd_lpc4330.cfg
    
    echo ✓ Created openocd_lpc4330.cfg
    echo   - Configured for ST-Link interface
    echo   - Modify if using different debugger
    echo.
)

REM Determine which file to program
set FIRMWARE_FILE=
if exist "build_lpc4330\drone_firmware.hex" (
    set FIRMWARE_FILE=build_lpc4330\drone_firmware.hex
    set FILE_TYPE=hex
) else if exist "build_lpc4330\drone_firmware.elf" (
    set FIRMWARE_FILE=build_lpc4330\drone_firmware.elf
    set FILE_TYPE=elf
)

echo Programming firmware...
echo   File: %FIRMWARE_FILE%
echo   Type: %FILE_TYPE%
echo.

REM Create programming commands
echo # OpenOCD programming commands> program_commands.cfg
echo init>> program_commands.cfg
echo reset halt>> program_commands.cfg
echo flash probe 0>> program_commands.cfg

if "%FILE_TYPE%"=="hex" (
    echo flash write_image erase %FIRMWARE_FILE%>> program_commands.cfg
) else (
    echo flash write_image erase %FIRMWARE_FILE% 0x1A000000>> program_commands.cfg
)

echo verify_image %FIRMWARE_FILE%>> program_commands.cfg
echo reset run>> program_commands.cfg
echo shutdown>> program_commands.cfg

echo Starting OpenOCD programming...
openocd -f openocd_lpc4330.cfg -f program_commands.cfg

if errorlevel 1 (
    echo.
    echo ERROR: Programming failed!
    echo.
    echo Troubleshooting:
    echo   1. Check debugger connection
    echo   2. Verify target power
    echo   3. Check openocd_lpc4330.cfg settings
    echo   4. Try different adapter speed
    echo.
    echo Alternative: Use firmware_uploader.py GUI
    pause
    exit /b 1
) else (
    echo.
    echo ==========================================
    echo  Programming Completed Successfully!
    echo ==========================================
    echo.
    echo Firmware programmed: %FIRMWARE_FILE%
    echo.
    echo Next steps:
    echo   1. Power cycle the drone
    echo   2. Check for boot messages via UART
    echo   3. Test basic functionality
    echo.
)

REM Cleanup
del program_commands.cfg 2>nul

pause